### PR TITLE
Harden against potential background crashes

### LINKED ISSUE #75: Crashing in background
Sometimes the app crashes in the background, and I only realize it a couple of hours after the crash by realizing the missing icon in the system tray.
See me not realizing the crash for two days :);
CleanShot 2023-06-02 at 22 12 31@2x

I want to supply some helpful info regarding this, but I need to figure out how we log things and get a reasonable trace to fix this issue.

Any help?

### PR DESCRIPTION
**Pull request by starbugs**
Fixes #75 

This adds two precautions to avoid future crashes:

1. `Process.launch()` can throw ObjC exceptions and those are now bridged to Swift and handled. `Process.launch()` is deprecated on macOS 14 or newer. So I added a `Process` extension that automatically uses the right method and provides exception handling in all cases.
2. The `WakaTime` state variables `lastFile` and `lastTime` are currently being read and written on a single worker thread and strictly don't require any thread safety guarantees for the time being. However, devs could break this in the future by accessing `lastFile` or `lastTime` on a separate thread concurrently. This has a potential to cause crashes, especially with concurrent writes. So I added an `Atomic` property wrapper that makes those two properties atomic.

### CODE REVIEW

File: WakaTime/Extensions/OptionalExtension.swift [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import Foundation
+
+extension Optional where Wrapped: Collection {
```
Comment (alanhamlett) [inline WakaTime/Extensions/OptionalExtension.swift:3]: Cool, I used this before in another project. Very helpful.

File: WakaTime/Extensions/ProcessExtension.swift [hunk 2]
```diff
@@ -0,0 +1,16 @@
+import Foundation
+
+extension Process {
+    // Runs process.launch() prior to macOS 13 or process.run() on macOS 13 or newer.
+    // Adds Swift exception handling to process.launch().
+    func execute() throws {
+        if #available(macOS 13.0, *) {
+            // Use Process.run() on macOS 13 or newer. Process.run() throws Swift exceptions.
+            try self.run()
```
Comment (alanhamlett) [inline WakaTime/Extensions/ProcessExtension.swift:9]: We need to catch and log these exceptions to `Console.app` and in the future also Crashlytics (#87).

File: WakaTime/Utils/Atomic.swift [hunk 3]
```diff
@@ -0,0 +1,28 @@
+import Foundation
+
+@propertyWrapper
+struct Atomic<Value> {
```
Comment (alanhamlett) [inline WakaTime/Utils/Atomic.swift:4]: 👍

File: WakaTime/WakaTime.swift [hunk 4]
```diff
@@ -263,21 +283,13 @@ class WakaTime {
...
-    func formatted() -> String {
-        let components = URLComponents(url: self, resolvingAgainstBaseURL: true)
-        let path = components?.path ?? ""
-        return path.replacingOccurrences(of: " ", with: "\\ ")
+        do {
+            // Use WakaTime's custom execute() method to run the process. This will call Process.launch()
+            // with ObjC exception bridging on macOS 12 or earlier and Process.run() on macOS 13 or newer.
+            try process.execute()
+        } catch {
+            print("Failed to run wakatime-cli: \(error)")
```
Comment (alanhamlett) [inline WakaTime/WakaTime.swift:291]: In the future we'll need to log these to Crashlytics in #87.

**Review by alanhamlett — APPROVED** [review]
Looks great, ready to merge!
